[workspace]
resolver = "2"

members = [
    
     "day-1-first", "day-1-second", "day-2-first", "day-2-second", "day-3-first", "day-3-second",
     
]

[workspace.dependencies]
project-root = "0.2.2"
