[package]
name = "day-6-second"
version = "0.1.0"
edition = "2024"

[dependencies]
project-root.workspace = true
regex = "1.11.1"
strum = { version = "0.26.3", features = ["strum_macros"] }
strum_macros = "0.26.4"
rayon = "1.7"
